function colors = getDistinctColors(numColors)
% liberally borrowed from:
% Tim Holy (2021). Generate maximally perceptually-distinct colors
% (https://www.mathworks.com/matlabcentral/fileexchange/29702-generate-maximally-perceptually-distinct-colors),
% MATLAB Central File Exchange. Retrieved October 15, 2021.
validateattributes(numColors, {'numeric'}, {'nonnegative', 'scalar'});
if 0 == numColors
    colors = [];
    return;
elseif 1 == numColors
    colors = [0 0 0];
    return;
end

% Generate a sizable number of RGB triples. This represents our space of
% possible choices. By starting in RGB space, we ensure that all of the
% colors can be generated by the monitor.
gridDivision = linspace(0, 1, numColors);
[R,G,B] = ndgrid(gridDivision,gridDivision,gridDivision);
rgbColors = [R(:) G(:) B(:)];

colors = zeros(numColors, 3);
prevColor = [1 1 1];
backgroundDist = inf(size(rgbColors,1),1);
for i = 1:numColors
    % displacement of last from all colors on list
    colorDisplacement = bsxfun(@minus, rgbColors, prevColor);
    colorDisplacementSqr = sum(colorDisplacement .^ 2, 2);
    % find farthest color from background.
    backgroundDist = min(colorDisplacementSqr, backgroundDist);
    [~, index] = max(backgroundDist);
    colors(i,:) = rgbColors(index,:);
    prevColor = rgbColors(index,:);
end
end



% ----------------------------------------------------------------------------
% Copyright (C) 2022 Vidrio Technologies, LLC
% 
% ScanImage (R) 2022 is software to be used under the purchased terms
% Code may be modified, but not redistributed without the permission
% of Vidrio Technologies, LLC
% 
% VIDRIO TECHNOLOGIES, LLC MAKES NO WARRANTIES, EXPRESS OR IMPLIED, WITH
% RESPECT TO THIS PRODUCT, AND EXPRESSLY DISCLAIMS ANY WARRANTY OF
% MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.
% IN NO CASE SHALL VIDRIO TECHNOLOGIES, LLC BE LIABLE TO ANYONE FOR ANY
% CONSEQUENTIAL OR INCIDENTAL DAMAGES, EXPRESS OR IMPLIED, OR UPON ANY OTHER
% BASIS OF LIABILITY WHATSOEVER, EVEN IF THE LOSS OR DAMAGE IS CAUSED BY
% VIDRIO TECHNOLOGIES, LLC'S OWN NEGLIGENCE OR FAULT.
% CONSEQUENTLY, VIDRIO TECHNOLOGIES, LLC SHALL HAVE NO LIABILITY FOR ANY
% PERSONAL INJURY, PROPERTY DAMAGE OR OTHER LOSS BASED ON THE USE OF THE
% PRODUCT IN COMBINATION WITH OR INTEGRATED INTO ANY OTHER INSTRUMENT OR
% DEVICE.  HOWEVER, IF VIDRIO TECHNOLOGIES, LLC IS HELD LIABLE, WHETHER
% DIRECTLY OR INDIRECTLY, FOR ANY LOSS OR DAMAGE ARISING, REGARDLESS OF CAUSE
% OR ORIGIN, VIDRIO TECHNOLOGIES, LLC's MAXIMUM LIABILITY SHALL NOT IN ANY
% CASE EXCEED THE PURCHASE PRICE OF THE PRODUCT WHICH SHALL BE THE COMPLETE
% AND EXCLUSIVE REMEDY AGAINST VIDRIO TECHNOLOGIES, LLC.
% ----------------------------------------------------------------------------
