classdef PicoQuantRemoteControllerPage < dabs.resources.configuration.ResourcePage
    properties
        etHost
        etStartDelaySeconds
    end
    
    methods
        function obj = PicoQuantRemoteControllerPage(hResource,hParent)
            obj@dabs.resources.configuration.ResourcePage(hResource,hParent);
        end
        
        function makePanel(obj,hParent)
            most.gui.uicontrol(...
                'Parent', hParent,...
                'Style', 'text',...
                'RelPosition', [24 29 120 20],...
                'Tag', 'txHost',...
                'String', 'Host address',...
                'HorizontalAlignment','right'...
                );
            obj.etHost = most.gui.uicontrol(...
                'Parent', hParent,...
                'Style', 'edit',...
                'String', {''},...
                'RelPosition', [150 27 120 20],...
                'Tag', 'etHost'...
                );
            
            most.gui.uicontrol(...
                'Parent', hParent,...
                'Style', 'text',...
                'RelPosition', [24 53 120 20],...
                'Tag', 'txStartDelaySeconds',...
                'String', 'Start delay [s]',...
                'HorizontalAlignment', 'right'...
                );
            
            obj.etStartDelaySeconds = most.gui.uicontrol(...
                'Parent', hParent,...
                'Style', 'edit',...
                'String', {''},...
                'RelPosition', [150 52 120 20],...
                'Tag', 'etStartDelaySeconds'...
                );
            
            most.gui.uicontrol(...
                'Parent', hParent,...
                'Style', 'pushbutton',...
                'String', 'Restore Defaults',...
                'RelPosition', [150 82 120 20],...
                'Callback', @(~,~)applyDefaults()...
            );
            
            function applyDefaults()
                obj.etHost.String = '192.168.43.3';
                obj.etStartDelaySeconds.String = '0';
                obj.apply();
            end
        end
        
        function redraw(obj)
            obj.etHost.String =...
                obj.hResource.hConfiguration.host;
            obj.etStartDelaySeconds.String =...
                num2str(obj.hResource.hConfiguration.startDelaySeconds);
        end
        
        function apply(obj)
            most.idioms.safeSetProp(...
                obj.hResource.hConfiguration,...
                'host',...
                obj.etHost.String...
                );
            most.idioms.safeSetProp(...
                obj.hResource.hConfiguration,...
                'startDelaySeconds',...
                str2double(obj.etStartDelaySeconds.String)...
                );
            
            obj.hResource.saveMdf();
            obj.hResource.reinit();
        end
        
        function remove(obj)
            obj.hResource.deleteAndRemoveMdfHeading();
        end
    end
end




% ----------------------------------------------------------------------------
% Copyright (C) 2022 Vidrio Technologies, LLC
% 
% ScanImage (R) 2022 is software to be used under the purchased terms
% Code may be modified, but not redistributed without the permission
% of Vidrio Technologies, LLC
% 
% VIDRIO TECHNOLOGIES, LLC MAKES NO WARRANTIES, EXPRESS OR IMPLIED, WITH
% RESPECT TO THIS PRODUCT, AND EXPRESSLY DISCLAIMS ANY WARRANTY OF
% MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.
% IN NO CASE SHALL VIDRIO TECHNOLOGIES, LLC BE LIABLE TO ANYONE FOR ANY
% CONSEQUENTIAL OR INCIDENTAL DAMAGES, EXPRESS OR IMPLIED, OR UPON ANY OTHER
% BASIS OF LIABILITY WHATSOEVER, EVEN IF THE LOSS OR DAMAGE IS CAUSED BY
% VIDRIO TECHNOLOGIES, LLC'S OWN NEGLIGENCE OR FAULT.
% CONSEQUENTLY, VIDRIO TECHNOLOGIES, LLC SHALL HAVE NO LIABILITY FOR ANY
% PERSONAL INJURY, PROPERTY DAMAGE OR OTHER LOSS BASED ON THE USE OF THE
% PRODUCT IN COMBINATION WITH OR INTEGRATED INTO ANY OTHER INSTRUMENT OR
% DEVICE.  HOWEVER, IF VIDRIO TECHNOLOGIES, LLC IS HELD LIABLE, WHETHER
% DIRECTLY OR INDIRECTLY, FOR ANY LOSS OR DAMAGE ARISING, REGARDLESS OF CAUSE
% OR ORIGIN, VIDRIO TECHNOLOGIES, LLC's MAXIMUM LIABILITY SHALL NOT IN ANY
% CASE EXCEED THE PURCHASE PRICE OF THE PRODUCT WHICH SHALL BE THE COMPLETE
% AND EXCLUSIVE REMEDY AGAINST VIDRIO TECHNOLOGIES, LLC.
% ----------------------------------------------------------------------------
