function aboutDialog()            
    p = most.gui.centeredScreenPos([80, 34],'characters');

    obj.hFig = most.idioms.figure(...
        'Units','characters',...
        'Color',most.constants.Colors.vidrioBlue,...
        'MenuBar','none',...
        'Name',scanimage.SI.version(),...
        'NumberTitle','off',...
        'Position',p,...
        'Resize','off',...
        'Visible','off');

    logoPanel = uipanel(...
        'Parent',obj.hFig,...
        'Units','characters',...
        'Clipping','on',...
        'BorderType','none',...
        'Position',[0 25 80 9],...
        'Tag','logopanel');

    hLogo = scanimage.util.ScanImageLogo(logoPanel,false);

    infoPanel = uipanel(...
        'Parent',obj.hFig,...
        'Units','characters',...
        'Clipping','on',...
        'BorderType','none',...
        'Position',[0 0 80 25],...
        'Tag','infopanel');

    hLM = scanimage.util.private.LM();
    hLM.showInfo(infoPanel);

    set(obj.hFig,'Visible','on');
    
    hLogo.animate();
end





% ----------------------------------------------------------------------------
% Copyright (C) 2022 Vidrio Technologies, LLC
% 
% ScanImage (R) 2022 is software to be used under the purchased terms
% Code may be modified, but not redistributed without the permission
% of Vidrio Technologies, LLC
% 
% VIDRIO TECHNOLOGIES, LLC MAKES NO WARRANTIES, EXPRESS OR IMPLIED, WITH
% RESPECT TO THIS PRODUCT, AND EXPRESSLY DISCLAIMS ANY WARRANTY OF
% MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.
% IN NO CASE SHALL VIDRIO TECHNOLOGIES, LLC BE LIABLE TO ANYONE FOR ANY
% CONSEQUENTIAL OR INCIDENTAL DAMAGES, EXPRESS OR IMPLIED, OR UPON ANY OTHER
% BASIS OF LIABILITY WHATSOEVER, EVEN IF THE LOSS OR DAMAGE IS CAUSED BY
% VIDRIO TECHNOLOGIES, LLC'S OWN NEGLIGENCE OR FAULT.
% CONSEQUENTLY, VIDRIO TECHNOLOGIES, LLC SHALL HAVE NO LIABILITY FOR ANY
% PERSONAL INJURY, PROPERTY DAMAGE OR OTHER LOSS BASED ON THE USE OF THE
% PRODUCT IN COMBINATION WITH OR INTEGRATED INTO ANY OTHER INSTRUMENT OR
% DEVICE.  HOWEVER, IF VIDRIO TECHNOLOGIES, LLC IS HELD LIABLE, WHETHER
% DIRECTLY OR INDIRECTLY, FOR ANY LOSS OR DAMAGE ARISING, REGARDLESS OF CAUSE
% OR ORIGIN, VIDRIO TECHNOLOGIES, LLC's MAXIMUM LIABILITY SHALL NOT IN ANY
% CASE EXCEED THE PURCHASE PRICE OF THE PRODUCT WHICH SHALL BE THE COMPLETE
% AND EXCLUSIVE REMEDY AGAINST VIDRIO TECHNOLOGIES, LLC.
% ----------------------------------------------------------------------------
