function m = str2map(s)
%STR2MAP Convert a string to a containers.Map object
% m = str2map(s)
% 
% The input string s should be in the format generated by map2str.

if isempty(s)
    m = containers.Map;
    return;
else
    s = [s ' | ']; % add last divider to make all key-val pairs identical
end

pat = '([^:|])+:([^|])+|';
toks = regexp(s,pat,'tokens');

keys = cellfun(@(x)strtrim(x{1}),toks,'UniformOutput',false);

% treat keys as numeric if they can all be converted successfully to numeric
numkeys = cellfun(@str2double,keys);
if ~any(isnan(numkeys))
    keys = numkeys;
end 

vals = cellfun(@(x)strtrim(x{2}),toks,'UniformOutput',false);
tfUnencodeable = strcmp(vals,'<unencodeable value>');
vals(tfUnencodeable) = {'[]'};
vals = cellfun(@eval,vals,'UniformOutput',false);

m = containers.Map(keys,vals);

end




% ----------------------------------------------------------------------------
% Copyright (C) 2022 Vidrio Technologies, LLC
% 
% ScanImage (R) 2022 is software to be used under the purchased terms
% Code may be modified, but not redistributed without the permission
% of Vidrio Technologies, LLC
% 
% VIDRIO TECHNOLOGIES, LLC MAKES NO WARRANTIES, EXPRESS OR IMPLIED, WITH
% RESPECT TO THIS PRODUCT, AND EXPRESSLY DISCLAIMS ANY WARRANTY OF
% MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.
% IN NO CASE SHALL VIDRIO TECHNOLOGIES, LLC BE LIABLE TO ANYONE FOR ANY
% CONSEQUENTIAL OR INCIDENTAL DAMAGES, EXPRESS OR IMPLIED, OR UPON ANY OTHER
% BASIS OF LIABILITY WHATSOEVER, EVEN IF THE LOSS OR DAMAGE IS CAUSED BY
% VIDRIO TECHNOLOGIES, LLC'S OWN NEGLIGENCE OR FAULT.
% CONSEQUENTLY, VIDRIO TECHNOLOGIES, LLC SHALL HAVE NO LIABILITY FOR ANY
% PERSONAL INJURY, PROPERTY DAMAGE OR OTHER LOSS BASED ON THE USE OF THE
% PRODUCT IN COMBINATION WITH OR INTEGRATED INTO ANY OTHER INSTRUMENT OR
% DEVICE.  HOWEVER, IF VIDRIO TECHNOLOGIES, LLC IS HELD LIABLE, WHETHER
% DIRECTLY OR INDIRECTLY, FOR ANY LOSS OR DAMAGE ARISING, REGARDLESS OF CAUSE
% OR ORIGIN, VIDRIO TECHNOLOGIES, LLC's MAXIMUM LIABILITY SHALL NOT IN ANY
% CASE EXCEED THE PURCHASE PRICE OF THE PRODUCT WHICH SHALL BE THE COMPLETE
% AND EXCLUSIVE REMEDY AGAINST VIDRIO TECHNOLOGIES, LLC.
% ----------------------------------------------------------------------------
